### ISSUE TITLE
Mutations must provide a CSRF token in the X-CSRF-TOKEN header

### ISSUE THREAD

**Issue by chillu** [Firesphere/silverstripe-graphql-jwt#22]
We've added CSRF protection to all mutations through https://github.com/silverstripe/silverstripe-graphql/commit/b59ba397ff42d8934bd2d9c932514f898c327f64 as part of a security fix. That was a tradeoff satisfying the current CMS use case, which is PHP session based. 

But it does get external modules like this into a chicken-and-egg situations: In order to get a JWT token, you need to authenticate to get a CSRF token. I've proposed to make this  opt out for mutations like this via https://github.com/silverstripe/silverstripe-graphql/issues/212.

Any other ideas on how to fix this in the short term?

/cc @unclecheese

**Comment by Firesphere** [comment]
This would entirely depend on the way the CSRF token is provided. If you can email me more detail around the how and what, I can have a look at what options are available.

I don't see any immediate short-term solution, besides an oAuth2 type flow, where a long local unique is exchanged for a short token?

**Comment by Firesphere** [comment]
I think @tractorcow is on this?

**Comment by unclecheese** [comment]
This is just going to add a bit of boilerplate to the JWT installation. You'll need to create a new `QueryHandler` implementation with whatever middlewares you want, and omit the CSRF middleware from that list, then add it to your controller as the second param:

```yaml
SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\QueryHandler\QueryHandlerInterface.default:
    properties:
      Middlewares:
        csrf: false
```

 ^ that should work
